### ISSUE TITLE
Support Binding Named Parameters

### ISSUE THREAD

**Issue by notkriswagner** [snowflakedb/libsnowflakeclient#114]
We want to be able to bind named parameters in SQL text, i.e. `select * from t where id=:id;`

**Comment by notkriswagner** [comment]
This is needed for snowflakedb/pdo_snowflake#68

**Comment by h-chaturvedi** [comment]
Resolved by commit [named_param_support](https://github.com/snowflakedb/libsnowflakeclient/commit/2294764ff2fec6635fb2c290fed50bd3eb1d7bb8)

**Comment by h-chaturvedi** [comment]
resolved by commit [named parameter support](https://github.com/snowflakedb/libsnowflakeclient/commit/2294764ff2fec6635fb2c290fed50bd3eb1d7bb8)
