### ISSUE TITLE
[Windows] Missing aws in deps-build

### ISSUE THREAD

**Issue by huyphams** [snowflakedb/libsnowflakeclient#116]
I'm using Visual Studio 15 (2017) to build snowflake lib but got some errors:

![screen shot 2018-11-12 at 4 06 26 pm](https://user-images.githubusercontent.com/3654622/48337245-00a30780-e695-11e8-9f19-dbe418ebebc2.png)

After checking the deps-build, there is no aws (darwin and linux have aws in deps-build)

**Comment by howryu** [comment]
@huyphams This is expected. I cannot checkin aws sdk to dep-build directory since the binary is too large. You have to build aws sdk by yourself. I checkin some scripts like `scripts/build_awssdk.bat`, you can try running that script to try building aws sdk.

**Comment by huyphams** [comment]
Thanks for the explanation, I will try to build it.

Btw, I have upgraded to the version 0.2.7 but it's crashed the app as soon as the connection was made, I will create an example and create a new issue for it.

Thanks for the supporting.

**Comment by howryu** [comment]
I will close this one.
