### ISSUE TITLE
Allow nil log_path.

### ISSUE THREAD

**Issue by huyphams** [snowflakedb/libsnowflakeclient#150]
We use libsnowflake in a database GUI client. In our particular situation, we do not need the client to create a log file so we do the global init:

```
      snowflake_global_init(nil, SF_LOG_FATAL, nil)
```
The problem is the [log_init(const char *log_path, SF_LOG_LEVEL log_level)](https://github.com/snowflakedb/libsnowflakeclient/blob/master/lib/client.c#L281) in the file lib/client.c return error which results in the global init fails, and it skips init [the header](https://github.com/snowflakedb/libsnowflakeclient/blob/master/lib/client.c#L504)

And final it crashes in the https://github.com/snowflakedb/libsnowflakeclient/blob/master/lib/connection.c#L280 when we attempt to establish a connection because the SF_HEADER_USER_AGENT is NULL.

**Comment by notkriswagner** [comment]
I'll add this to the backlog

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
