### ISSUE TITLE
Inconsistent behavior for put command on AWS when overwrite=false

### ISSUE THREAD

**Issue by SimbaGithub** [snowflakedb/libsnowflakeclient#165]
According to the document, https://docs.snowflake.net/manuals/sql-reference/sql/put.html
when overwrite=false, the uploading should be skipped if there is an existing file with the same name.
But on AWS, the uploading is skipped only when both file name and checksum are the same. It also could cause crash if the server doesn't return checksum of the existing file. On Azure, only file name is checked.

We need consistent behavior across the cloud providers, change the behavior on AWS so that only file name is checked.

**Comment by rvishureddy** [comment]
Are you tracking the crash as part of this JIRA.

**Comment by SimbaGithub** [comment]
> Are you tracking the crash as part of this issue.

Yup, add it into the issue description.
