### ISSUE TITLE
SNOW-153414: exceptionSQLSTATE[08001] [240012] curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by slloyd88** [snowflakedb/libsnowflakeclient#196]
I am running Apache on Windows 10 with php 7.2  on localhost.
When trying to connect I get this error.

exceptionSQLSTATE[08001] [240012] curl_easy_perform() failed: SSL peer certificate or SSH remote key was not OK
I was reading another but and saw you suggesting setting SNOWFLAKE_TEST_CA_BUNDLE_FILE to the PATH of the cacert.pem.  This made no difference.

**Comment by slloyd88** [comment]
I also enabled localhost to SSL and still got the same error.

**Comment by jdanielmyers** [comment]
Can you confirm that you are using an SSL proxy?

https://community.snowflake.com/s/article/CURLerror-SSL-peer-certificate-or-SSH-remote-key-was-not-OK-during

**Comment by sfc-gh-hkapre** [comment]
Closing since there has been no response in over a year.
