### ISSUE TITLE
SNOW-172949: An insert or update query always returns zero count for 'number of rows inserted/updated'

### ISSUE THREAD

**Issue by hankinsoft** [snowflakedb/libsnowflakeclient#216]
If you run a INSERT statement through this library, it returns one record with one column titled 'number of rows inserted'. The value for this record is always zero (although snowflake_affected_rows does return the proper count).

If you run a UPDATE statement through this library, it returns one record with two columns titled 'number of rows updated' and 'number of multi-joined rows updated'. The value for this record is always zero (although snowflake_affected_rows does return a count -- but for only one of those columns).

**Comment by sfc-gh-igarish** [comment]
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.
