### ISSUE TITLE
SNOW-176651:  Wrong result with timestamp with precision 0

### ISSUE THREAD

**Issue by sfc-gh-smirzaei** [snowflakedb/libsnowflakeclient#221]
For a simple queries like following:
`select '2020-07-1'::timestamp_ltz(0)`
`select '2020-07-1'::timestamp_ntz(0)`
`select '2020-07-1'::timestamp_tz(0)`
`select '2020-07-1'::timestamp(0)`
The results is `Dec 30 1899...`. I.e., tm_year, tm_mon ... fields of tm are all uninitialized.

**Comment by sfc-gh-smirzaei** [comment]
I have a fix, will send it for review soon

**Comment by sfc-gh-jtang** [comment]
@sfc-gh-igarish can you check if it's still an open issue? looks we had a fix to review about 3 years ago :)

**Comment by sfc-gh-igarish** [comment]
PR#222 has the fix.
