### ISSUE TITLE
Better TIMESTAMP_LTZ, TIMESTAMP_NTZ and TIMESTAMP_TZ support

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/libsnowflakeclient#25]
POSIX time functions are not portable across multiple platforms.
gmtime doesn't work on Windows before year 1970, for example, OSX converts it to Julian calendar before year 1600 or so.

We need better timestamp supports.

**Comment by notkriswagner** [comment]
Related to #33

**Comment by notkriswagner** [comment]
Implemented in #94
