### ISSUE TITLE
Add logging interface to underlying libraries. 

### ISSUE THREAD

**Issue by howryu** [snowflakedb/libsnowflakeclient#37]
libsnowflakeclient depends multiple libraries. Logs from curl, aws-sdk should be captured. We need to add some interface to capture logs from those libraries and add namespace before each entry.

More specifically,
libcurl has both options. `CURLOPT_VERBOSE` and `CURLOPT_DEBUGFUNCTION`
aws sdk provide `FormattedLogSystem` class https://sdk.amazonaws.com/cpp/api/0.14.3/class_aws_1_1_utils_1_1_logging_1_1_formatted_log_system.html

**Comment by smtakeda** [comment]
Ideally one log file include all logs along with the name spaces.

**Comment by smtakeda** [comment]
Started working on the initial framework.

**Comment by smtakeda** [comment]
Regarding log formats, does it make sense to use tab as separator of log elements instead of spaces? It would be much easier to process the log by scripts.

**Comment by sfc-gh-dszmolka** [comment]
closing this old issue
