### ISSUE TITLE
SNOW-585111: Snowflake-Specific Proxy Config

### ISSUE THREAD

**Issue by cjsfj** [snowflakedb/libsnowflakeclient#417]
Currently all of the proxy server environment variables are system-wide:

https://github.com/snowflakedb/libsnowflakeclient/blob/3503882ab1185753f4635d1418778332251cc254/cpp/util/Proxy.cpp#L70-L85

Would love to see an option to set a proxy that is specific to snowflake only and not system-wide.

Thank you,

CJ

**Comment by sfc-gh-dszmolka** [comment]
this library is used internally by other Snowflake drivers so all enhancement effort is focused on the particular drivers utilizing this library. Meaning, I'm not sure if this will be ever prioritized, unfortunately.

**Comment by sfc-gh-dszmolka** [comment]
apparently i was missing quite some stuff, and individual proxy handling (non-envvar) was implemented with https://github.com/snowflakedb/libsnowflakeclient/pull/479

not documented, tho, we'll work on that

**Comment by sfc-gh-dszmolka** [comment]
closing this issue since the capability has been already implemented; the readme will be updated in the future
