### ISSUE TITLE
Some long lasting queries issue

### ISSUE THREAD

**Issue by SaberMirzaei** [snowflakedb/libsnowflakeclient#49]
If I'm not making any mistake in using libSFClient, some long lasting queries will finish with status 0, without actually finishing and returning anything.
For instance some query like 'select 11 as c1 from table(generator(timelimit=>100));' will finish in less than 50 sec with status = success and no results.

**Comment by smtakeda** [comment]
@SaberMirzaei I tried this and traced the value:```
select seq4(),randstr(1000,random()) from table(generator(timelimit=>100))
```
But I could not reproduce the problem. I got around 3 million records for the local test environment.

**Comment by smtakeda** [comment]
See the test case I ran:
https://github.com/snowflakedb/libsnowflakeclient/blob/fix-49/tests/test_large_result_set.c#L64
and the tests:
https://travis-ci.org/snowflakedb/libsnowflakeclient/builds/373230600

**Comment by smtakeda** [comment]
Note https://travis-ci.org/snowflakedb/libsnowflakeclient/builds/373230600 timeout.
I won't merge the branch fix-49 btw.

**Comment by SaberMirzaei** [comment]
I'm closing this since this was an issue caused by failing authentication when doing ping pong with GS.
