### ISSUE TITLE
Deprecated OpenSSL functions are used

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/libsnowflakeclient#56]
https://www.openssl.org/docs/man1.1.0/crypto/ERR_load_crypto_strings.html

@howryu, I just found that some OpenSSL functions are deprecated but used in the code.
cpp/crypto/Cryptor.cpp
https://github.com/snowflakedb/libsnowflakeclient/blob/master/cpp/crypto/Cryptor.cpp#L272

Can you take a look?

**Comment by howryu** [comment]
I will take a look.

**Comment by sfc-gh-ext-simba-hx** [comment]
The fix is released in libsnowflakeclient 0.6.19. Close.
