### ISSUE TITLE
EncryptionProvider has ECB for key encryption, Azure blob encryption metadata has CBC.  

### ISSUE THREAD

**Issue by lpjette** [snowflakedb/libsnowflakeclient#743]
During a _COPY INTO @azure_stage from some.data_, where **azure_stage** is using client side encryption, with a master key. [docs](https://docs.snowflake.com/user-guide/data-load-azure-config#data-file-encryption), the resulting encryption metadata is incorrect.

The encryption algorithm in the metadata seems to be hardcoded to AES_CBC_256 for key encryption. (key wrapping)  
[sf_sprintf(buf, sizeof(buf), "{\"EncryptionMode\":\"FullBlob\",\"WrappedContentKey\":{\"KeyId\":\"symmKey1\",\"EncryptedKey\":\"%s\",\"Algorithm\":\"AES_CBC_256\"},\"EncryptionAgent\":{\"Protocol\":\"1.0\",\"EncryptionAlgorithm\":\"AES_CBC_256\"},\"ContentEncryptionIV\":\"%s\", \"KeyWrappingMetadata\":{\"EncryptionLibrary\":\"Java 5.3.0\"}}", enkek64.c_str(), iv64.c_str());](https://github.com/snowflakedb/libsnowflakeclient/blob/526ac94b93e640c295ad4dc89b5fc5adc857076c/cpp/SnowflakeAzureClient.cpp#L225)

External client libraries are failing to decrypt because of the incorrect algorithm mode being retrieved through the metadata for unwrapping the encryption key. The Encryption Provider has ECB hardcoded. 
[Crypto::CryptoMode::ECB](https://github.com/snowflakedb/libsnowflakeclient/blob/526ac94b93e640c295ad4dc89b5fc5adc857076c/cpp/EncryptionProvider.cpp#L28)

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue and providing all the details ! we'll take a look.

**Comment by sfc-gh-dszmolka** [comment]
Discussing this issue with the team. `AES_CBC_256` is used in all Snowflake drivers, for data encryption.

`AES_ECB` is used for key encryption, and its size can be 128 or 256 bits and is configured in `CLIENT_ENCRYPTION_KEY_SIZE` upon stage creation, alongside with the master key and encryption type. 

Speaking about which, we would like to reproduce this issue. Do you have a queryId perhaps from the stage creation which I could look up, or the extact statements used how you created the stage ? Thank you in advance !

**Comment by lpjette** [comment]
I created the Azure stage with 

`CREATE OR REPLACE STAGE my_azure_stage
  URL='azure://xxxxxxxx.blob.core.windows.net/some_container'
  CREDENTIALS=(AZURE_SAS_TOKEN='?sp=rwdl&st=2024-08-29T21:17:12Z&se=2024-08-30T05:17:12Z&spr=https&sv=2022-11-02&sr=c&sig=Kx...')
  ENCRYPTION=(TYPE='AZURE_CSE' MASTER_KEY = 'MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2Nzg=')
  FILE_FORMAT = my_csv_format;`  
  
Regardless of the key or key size I used, the blob metadata is always indicating the AES_CBC_256 for the key wrapping algorithm, which is misleading as the key wrapping algorithm used is truly AES_ECB. 

On another note, interestingly enough, the ContentEncryptionIV seems to always be the same, which AES_CBC prescribes against as the reuse of the same IV for different content is prone to cryptographic attacks. It should always be random.

**Comment by sfc-gh-dstempniak** [comment]
@lpjette Data in the blob are always encoded by `AES_CBC_256` with key id `symmKey1`. Only the key used for data encoding is encoded by the MASTER_KEY - `AES_ECB`.
Please check this use case for Python: https://community.snowflake.com/s/article/Decryption-failed-error-trying-read-data-that-is-unloaded-from-Snowflake-using-Azure-client-side-encryption

**Comment by sfc-gh-dszmolka** [comment]
marking this one as closed as it has been without response for a month now, but please feel free to comment with the details and we can reopen and assist further if necessary
