### ISSUE TITLE
SF_STMT->total_fieldcount returns -1 sometimes after query is executed

### ISSUE THREAD

**Issue by notkriswagner** [snowflakedb/libsnowflakeclient#76]
The total_fieldcount field in SF_STMT struct sometimes returns -1 after a DDL query is executed. For DDL queries, this field should be set to 0.

**Comment by notkriswagner** [comment]
Looks like this is caused when an empty JSON response is returned from the server. Investigating why we get back an empty JSON response.

**Comment by notkriswagner** [comment]
The empty JSON response occurs when we incorrectly label a query as being a PUT/GET query when it is not. An example of this is the query `CREATE OR REPLACE TABLE obfuscated_table_name (daily_budget number(38,6))`. The regex pattern matches to the "get" part of the column name "daily_budget" and incorrectly labels this as a PUT/GET query.

The regex pattern at fault is `^([ ]*\\/*.*\\/*[ ]*)*(put|get)[ ]+`. When I put this through a regex tester (and from looking at the snowflake-connector-python), I see that changing the first regex group to be a non-capturing group (`^(?>[ ]*\\/*.*\\/*[ ]*)*(put|get)[ ]+`) solves the problem and the false positive matches go away.

The `regex.h` C library does not have support for non-capturing groups in regex patterns. There are C libraries that do have support for non-capturing groups, such as [PCRE2](https://www.pcre.org/), but that would also mean adding another library to the C API

**Comment by smtakeda** [comment]
PCRE2 seems overkills just for PUT and GET command detection. @notkriswagner isn't the problem the existing regex pattern is not specific enough for it? You could capture the groups and can ignore them?

**Comment by smtakeda** [comment]
`REG_NOSUB` looks like to report success or failure.

**Comment by smtakeda** [comment]
It is very strange `^` BOL is ignored...
```
regcomp(&put_get_regex, "^([ ]*\\/*.*\\/*[ ]*)*(put|get)[ ]+",
            REG_ICASE | REG_EXTENDED);
```
PUT and GET must start from the beginning excluding comments.

**Comment by notkriswagner** [comment]
In C with `regex.h` you can't ignore groups that you capture (see: https://stackoverflow.com/questions/40816011/posix-regular-expression-non-capturing-group).

The problem is the part that is supposed to ignore the comments. I'm trying to figure out how to make it more restrictive without using a non-capturing group.

**Comment by smtakeda** [comment]
@notkriswagner can you put the pointer to the code change? Just push your branch to here for review. 

Btw, I'm still trying to understand why the original regex didn't work and non-grouping would fix. Please elaborate why `^` doesn't work to match the beginning of a string and how non-grouping helps.

**Comment by notkriswagner** [comment]
I'm not sure exactly why the non-grouping case works and the other case doesn't work, but the python connector uses non-grouping (which works) and when I change the C API regex to use non-grouping in the online regex tester, it works.

I've actually come up with a regex string that I believe would work for the tests cases I've posted. I'll push a code change for your to review soon.
