### ISSUE TITLE
Add PUT and GET support to C/C++ API

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/libsnowflakeclient#8]
https://github.com/snowflakedb/pdo_snowflake/issues/102

- Add C++ API on top of C API
- Add PUT and GET support to C++ API only.

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-vreddy can you confirm this is completed and close this?

**Comment by sfc-gh-dszmolka** [comment]
PUT/GET is already supported
