### ISSUE TITLE
Implement OCSP Validation

### ISSUE THREAD

**Issue by notkriswagner** [snowflakedb/libsnowflakeclient#90]
In order to be super secure, the C API needs to support OCSP validation.

**Comment by smtakeda** [comment]
Look into ODBC curl source code that already have OCSP patch. Basically all you have to do is copy sf_ocsp.{h,c} and update relevant sources. The curl version for both ODBC and libsnowflakeclient are the same.

**Comment by notkriswagner** [comment]
Fixed in #96
